name: Persistence Tests
on:
  pull_request:
  push:
    branches: [main]
jobs:
  persistence-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      dynamodb:
        image: amazon/dynamodb-local:2.6.1
        ports: ['8000:8000']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
      - run: yarn install --frozen-lockfile --network-timeout 600000
      - run: yarn test:integration
      - run: yarn package:lambdas
